var SELECT_CONSULTA_INCLUDE_PACIENTE_MEDICO_COBERTURA = '''
  SELECT CS.ID_CONSULTA, CS.DATA_CONSULTA, CS.ID_PACIENTE, CS.ID_COBERTURA, P.NOME_PACIENTE, M.ID_MEDICO, M.NOME_MEDICO, CB.DSC_COBERTURA
  FROM CONSULTA CS
  JOIN PACIENTE P ON P.ID_PACIENTE = CS.ID_PACIENTE
  JOIN MEDICO M ON M.ID_MEDICO = CS.ID_MEDICO
  JOIN COBERTURA CB ON CB.ID_COBERTURA = CS.ID_COBERTURA
''';
