var DDL_LIST = [
  ESTADO_DDL,
  ENDERECO_DDL,
  MEDICO_DDL,
];
var DROP_LIST = [
  DROP_MEDICO,
  DROP_ENDERECO,
  DROP_ESTADO,
];

var DROP_ESTADO = 'DROP TABLE ESTADO';
var DROP_ENDERECO = 'DROP TABLE ENDERECO';
var DROP_MEDICO = 'DROP TABLE MEDICO';

var ESTADO_DDL = '''
  CREATE TABLE IF NOT EXISTS ESTADO (
    ID_ESTADO INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME_ESTADO TEXT,
    SIGLA TEXT
  )
''';

var ENDERECO_DDL = '''
  CREATE TABLE IF NOT EXISTS ENDERECO (
    ID_ENDERECO INTEGER PRIMARY KEY AUTOINCREMENT,
    CIDADE TEXT,
    LOGRADOURO TEXT,
    CEP TEXT,
    ID_ESTADO INTEGER,
    FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
  )
''';

var MEDICO_DDL = '''
  CREATE TABLE IF NOT EXISTS MEDICO (
    ID_MEDICO INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME_MEDICO TEXT,
    CRM INTEGER,
    TELEFONE INTEGER,
    ID_ENDERECO INTEGER,
    FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO)
  )
''';
