var DDL_LIST = [
  USUARIO_DDL,
  ESTADO_DDL,
  ENDERECO_DDL,
  ESPECIALIDADE_DDL,
  MEDICO_DDL,
  COBERTURA_DDL,
  PACIENTE_DDL,
  CONSULTA_DDL,
];
var DROP_LIST = [
  DROP_CONSULTA,
  DROP_MEDICO,
  DROP_PACIENTE,
  DROP_ENDERECO,
  DROP_COBERTURA,
  DROP_ESPECIALIDADE,
  DROP_USUARIO,
  DROP_ESTADO,
];

var DROP_CONSULTA = 'DROP TABLE IF EXISTS CONSULTA';
var DROP_USUARIO = 'DROP TABLE IF EXISTS USUARIO';
var DROP_ESTADO = 'DROP TABLE IF EXISTS ESTADO';
var DROP_ENDERECO = 'DROP TABLE IF EXISTS ENDERECO';
var DROP_MEDICO = 'DROP TABLE IF EXISTS MEDICO';
var DROP_ESPECIALIDADE = 'DROP TABLE IF EXISTS ESPECIALIDADE';
var DROP_COBERTURA = 'DROP TABLE IF EXISTS COBERTURA';
var DROP_PACIENTE = 'DROP TABLE IF EXISTS PACIENTE';

var USUARIO_DDL = '''
  CREATE TABLE IF NOT EXISTS USUARIO (
    ID_USUARIO INTEGER PRIMARY KEY AUTOINCREMENT,
    LOGIN TEXT UNIQUE NOT NULL,
    SENHA TEXT NOT NULL
  )
''';
var ESTADO_DDL = '''
  CREATE TABLE IF NOT EXISTS ESTADO (
    ID_ESTADO INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME_ESTADO TEXT  NOT NULL,
    SIGLA TEXT  NOT NULL
  )
''';

var ENDERECO_DDL = '''
  CREATE TABLE IF NOT EXISTS ENDERECO (
    ID_ENDERECO INTEGER PRIMARY KEY AUTOINCREMENT,
    CIDADE TEXT  NOT NULL,
    LOGRADOURO TEXT  NOT NULL,
    CEP TEXT NOT NULL,
    ID_ESTADO INTEGER NOT NULL,
    FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
  )
''';

var MEDICO_DDL = '''
  CREATE TABLE IF NOT EXISTS MEDICO (
    ID_MEDICO INTEGER PRIMARY KEY ,
    NOME_MEDICO TEXT NOT NULL,
    CRM INTEGER NOT NULL,
    ID_ESPECIALIDADE INTEGER NOT NULL,
    FOREIGN KEY(ID_ESPECIALIDADE) REFERENCES ESPECIALIDADE(ID_ESPECIALIDADE),
    FOREIGN KEY (ID_MEDICO) REFERENCES USUARIO(ID_USUARIO)
  )
''';

var ESPECIALIDADE_DDL = '''
  CREATE TABLE IF NOT EXISTS ESPECIALIDADE (
    ID_ESPECIALIDADE INTEGER PRIMARY KEY AUTOINCREMENT,
    DSC_ESPECIALIDADE TEXT NOT NULL
  )
''';
var COBERTURA_DDL = '''
  CREATE TABLE IF NOT EXISTS COBERTURA (
    ID_COBERTURA INTEGER PRIMARY KEY AUTOINCREMENT,
    DSC_COBERTURA TEXT NOT NULL
  )
''';

var PACIENTE_DDL = '''
  CREATE TABLE IF NOT EXISTS PACIENTE (
    ID_PACIENTE INTEGER PRIMARY KEY ,
    NOME_PACIENTE TEXT NOT NULL,
    DAT_NASCIMENTO TEXT NOT NULL,
    TELEFONE_PACIENTE INTEGER NOT NULL,
    CPF_PACIENTE INTEGER NOT NULL,
    RG_PACIENTE INTEGER NOT NULL,
    ID_ENDERECO INTEGER NOT NULL,
    FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO),
    FOREIGN KEY (ID_PACIENTE) REFERENCES USUARIO(ID_USUARIO)
  )
''';


var CONSULTA_DDL = '''
  CREATE TABLE IF NOT EXISTS CONSULTA (
    ID_CONSULTA INTEGER PRIMARY KEY,
    DATA_CONSULTA TEXT NOT NULL,
    ID_PACIENTE INTEGER NOT NULL,
    ID_MEDICO INTEGER NOT NULL,
    ID_COBERTURA INTEGER NOT NULL,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID_PACIENTE),
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO (ID_MEDICO),
    FOREIGN KEY (ID_COBERTURA) REFERENCES COBERTURA (ID_COBERTURA)
  )
''';