var SELECT_ENDERECO_INCLUDE_ESTADO = '''
  SELECT EN.ID_ENDERECO, EN.CIDADE, EN.LOGRADOURO, EN.CEP, ES.ID_ESTADO, ES.NOME_ESTADO, ES.SIGLA
  FROM ENDERECO EN
  JOIN ESTADO ES ON ES.ID_ESTADO = EN.ID_ESTADO
''';