var CREATE_TABLE_ENDERECOS = """
  CREATE TABLE IF NOT EXISTS  ENDERECOS (
    ID INTEGER PRIMARY KEY,
    CIDADE TEXT,
    LOGRADOURO TEXT,
    CEP TEXT,
    ID_ESTADO INTEGER
  )
""";

var INSERT_ENDERECOS = 'INSERT INTO TABLE ENDERECOS (CIDADE, LOGRADOURO, CEP, ID_ESTADO) VALUES (?, ?, ?, ?)';

var DELETE_ENDERECOS = 'DELETE FROM ENDERECOS WHERE ID = ?';

var UPDATE_ENDERECOS = 'UPDATE ENDERECOS SET CIDADE = ?, LOGRADOURO = ?, CEP = ?, ID_ESTADO = ? WHERE ID = ?';