var CREATE_TABLE_ESTADOS = """
  CREATE TABLE IF NOT EXISTS ESTADOS (
    ID INTEGER PRIMARY KEY, SIGLA TEXT, NOME TEXT
  )
""";


var INSERT_ESTADOS = 'INSERT INTO TABLE ESTADOS (SIGLA, NOME) VALUES (?, ?)';

var DELETE_ESTADOS = 'DELETE FROM ESTADOS WHERE ID = ?';

var UPDATE_ESTADOS = 'UPDATE ESTADOS SET SIGLA = ?, NOME = ? WHERE ID = ?';