var SELECT_MEDICO_INCLUDE_ESPECIALIDADE = '''
  SELECT M.ID_MEDICO, M.NOME_MEDICO, M.CRM, ES.ID_ESPECIALIDADE, ES.DSC_ESPECIALIDADE
  FROM MEDICO M
  JOIN ESPECIALIDADE ES ON ES.ID_ESPECIALIDADE = M.ID_ESPECIALIDADE
''';