var SELECT_MEDICO_INCLUDE_ENDERECO = '''
  SELECT M.ID_MEDICO, M.NOME_MEDICO, M.CRM, M.TELEFONE, EN.ID_ENDERECO, EN.CIDADE, EN.LOGRADOURO, EN. 
  FROM MEDICO M
  JOIN ENDERECO EN ON M.ID_ENDERECO = M.ID_ENDERECO
''';