var SELECT_PACIENTE_INCLUDE_ENDERECO = '''
  SELECT 
    PA.ID_PACIENTE, PA.NOME_PACIENTE, PA.DAT_NASCIMENTO, PA.TELEFONE_PACIENTE, 
    PA.CPF_PACIENTE, PA.RG_PACIENTE, EN.ID_ENDERECO, EN.CIDADE, EN.LOGRADOURO,
    EN.CEP 
  FROM PACIENTE PA
  JOIN ENDERECO EN ON EN.ID_ENDERECO = PA.ID_ENDERECO 
''';

