var CREATE_TABLE_PACIENTES = """
  CREATE TABLE IF NOT EXISTS PACIENTES (
    ID INTEGER PRIMARY KEY;
    NOME TEXT,
    SEXO INTEGER,
    NASCIMENTO DATE,
    ID_ENDERECO INTEGER,
    ID_PLANO INTEGER
  )
""";

var INSERT_TABLE_PACIENTES = """
  INSERT INTO PACIENTES (NOME, SEXO, NASCIMENTO, ID_ENDERECO, ID_PLANO)
  VALUES (?, ?, ?, ?, ?)
""";

var UPDATE_TABLE_PACIENTES = """
  UPDATE PACIENTES
  SET NOME = ?, SEXO = ?, NASCIMENTO = ?, ID_ENDERECO = ?, ID_PLANO = ?
  WHERE ID = ?
""";

var DELETE_TABLE_PACIENTES = """
  DELETE FROM PACIENTES WHERE ID = ?
""";