var POPULATE_USUARIO = [
  'INSERT INTO USUARIO (ID_USUARIO, LOGIN, SENHA) VALUES (1, "admin", "admin")',
  'INSERT INTO USUARIO (ID_USUARIO, LOGIN, SENHA) VALUES (2, "paciente", "paciente")',
  'INSERT INTO USUARIO (ID_USUARIO, LOGIN, SENHA) VALUES (3, "medico", "medico")',
];
var POPULATE_ESTADOS = [
  'INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO, SIGLA) VALUES (1, "Sergipe", "SE")',
  'INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO, SIGLA) VALUES (2, "Bahia", "BA")',
  'INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO, SIGLA) VALUES (3, "Rio de Janeiro", "RJ")',
  'INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO, SIGLA) VALUES (4, "Pernambuco", "PE")',
];
var POPULATE_ENDERECO = [
  'INSERT INTO ENDERECO (ID_ENDERECO, CIDADE, LOGRADOURO, CEP, ID_ESTADO) VALUES (1, "Aracaju", "Luzia", "49045700", 1)',
];
var POPULATE_ESPECIALIDADE = [
  'INSERT INTO ESPECIALIDADE (ID_ESPECIALIDADE, DSC_ESPECIALIDADE) VALUES (1, "Cardiologista")',
  'INSERT INTO ESPECIALIDADE (ID_ESPECIALIDADE, DSC_ESPECIALIDADE) VALUES (2, "Neurologista")',
];
var POPULATE_MEDICO = [
  'INSERT INTO MEDICO (ID_MEDICO, NOME_MEDICO, CRM, ID_ESPECIALIDADE) VALUES (3, "Arthur", 123, 1)',
];
var POPULATE_COBERTURA = [
  'INSERT INTO COBERTURA (ID_COBERTURA, DSC_COBERTURA) VALUES (1, "VIP")',
  'INSERT INTO COBERTURA (ID_COBERTURA, DSC_COBERTURA) VALUES (2, "Simples")',
];
var POPULATE_PACIENTE = [
  '''
  INSERT INTO PACIENTE (ID_PACIENTE, NOME_PACIENTE, DAT_NASCIMENTO, CPF_PACIENTE, RG_PACIENTE, TELEFONE_PACIENTE, ID_ENDERECO) VALUES (2, "Arthur", "11/05/2020", 12312312312, 12312312, 11111111, 1)   
  ''',
];
