var SELECT_IS_USUARIO_PACIENTE = '''
  SELECT 1 FROM PACIENTE
  WHERE ID_PACIENTE = (SELECT ID_USUARIO FROM USUARIO WHERE LOGIN = ?)
  LIMIT 1
''';
var SELECT_IS_USUARIO_MEDICO = '''
  SELECT 1 FROM MEDICO
  WHERE ID_MEDICO = (SELECT ID_USUARIO FROM USUARIO WHERE LOGIN = ?)
  LIMIT 1
''';
