var SELECT_IS_USUARIO_PACIENTE = '''
  SELECT 1 FROM PACIENTE
  WHERE ID_USUARIO = (SELECT ID_USUARIO FROM USUARIO WHERE LOGIN = ?)
  LIMIT 1
''';
var SELECT_IS_USUARIO_MEDICO = '''
  SELECT M.ID_USUARIO, M.CRM, M.NOME_MEDICO, M.ID_ESPECIALIDADE, U.LOGIN, U.SENHA  
  FROM MEDICO M
  JOIN USUARIO U ON U.ID_USUARIO = M.ID_USUARIO
  WHERE U.LOGIN = ?
  LIMIT 1
''';
